# Generated by Django 4.2.4 on 2023-10-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('R_name', models.CharField(max_length=50)),
                ('R_address', models.CharField(max_length=50)),
                ('R_loc', models.CharField(max_length=50)),
                ('R_phone', models.IntegerField(max_length=10)),
                ('R_parking', models.CharField(max_length=5)),
                ('R_pet', models.CharField(max_length=5)),
            ],
        ),
    ]
