# Generated by Django 4.2.4 on 2023-10-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='R_apc',
            field=models.CharField(default='Rs 5000', max_length=20),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='R_timings',
            field=models.CharField(default='6am to 9pm', max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='R_parking',
            field=models.CharField(default=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='R_pet',
            field=models.CharField(default=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='R_phone',
            field=models.IntegerField(),
        ),
    ]
