# Generated by Django 4.2.4 on 2023-10-03 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_r_apc_restaurant_r_timings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='R_loc',
        ),
    ]
