# Generated by Django 4.2.4 on 2023-10-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_remove_restaurant_r_loc'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='R_cu',
            field=models.CharField(default=['a', 'b', 'c'], max_length=120),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='R_more_info',
            field=models.CharField(default=['ac', 'bd'], max_length=200),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='R_pay',
            field=models.CharField(default='Cash or Cards Accepted', max_length=50),
        ),
    ]
