# Generated by Django 4.2.4 on 2023-10-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_restaurant_r_cu_restaurant_r_more_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='R_phone',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
