# Generated by Django 4.2.4 on 2023-10-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_alter_restaurant_r_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='R_phone',
            field=models.BigIntegerField(default='1234567890'),
        ),
    ]
