# Generated by Django 4.2.4 on 2023-10-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_alter_restaurant_r_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='R_phone',
            field=models.CharField(max_length=50),
        ),
    ]
