# Generated by Django 4.2.4 on 2023-10-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_alter_restaurant_r_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='R_apc',
            field=models.CharField(default='Rs 5000', max_length=500),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='R_timings',
            field=models.CharField(default='6am to 9pm', max_length=500),
        ),
    ]
