# Generated by Django 4.2.4 on 2023-10-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_alter_restaurant_r_cu_alter_restaurant_r_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='R_reserve',
            field=models.CharField(default='Yes', max_length=5),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='R_seat',
            field=models.CharField(default='Indoor Seating', max_length=50),
        ),
    ]
